pycodestyle:
    max-line-length: 100  # Default is 79 in PEP8
    ignore:  # Errors and warnings to ignore
    exclude:
        - "./docs/*"
        - "*/build/*"
        - "*/migrations/*"

# E401: multiple imports on one line
