#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by bootstrap.py. Please use
# bootstrap.py to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

set -euv

django-admin runserver 24817 >> ~/django_runserver.log 2>&1 &
sleep 5

cd "${TRAVIS_BUILD_DIR}"

if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
  echo "--- Performance Tests ---"
  pytest -vv -r sx --color=yes --pyargs --durations=0 pulp_file.tests.performance
else
  exit 0
fi
