# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pulp_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Content')),
                ('path', models.TextField()),
                ('digest', models.TextField()),
            ],
            bases=('pulp_app.content',),
        ),
        migrations.CreateModel(
            name='FileImporter',
            fields=[
                ('importer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Importer')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.importer',),
        ),
        migrations.CreateModel(
            name='FilePublisher',
            fields=[
                ('publisher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulp_app.Publisher')),
            ],
            options={
                'abstract': False,
            },
            bases=('pulp_app.publisher',),
        ),
        migrations.AlterUniqueTogether(
            name='filecontent',
            unique_together=set([('path', 'digest')]),
        ),
    ]
