# Generated by Django 2.2.6 on 2019-11-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191104_2000'),
        ('file', '0003_auto_20191014_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFileSystemExporter',
            fields=[
                ('filesystemexporter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='file_filefilesystemexporter', serialize=False, to='core.FileSystemExporter')),
            ],
            options={
                'default_related_name': '%(app_label)s_%(model_name)s',
            },
            bases=('core.filesystemexporter',),
        ),
    ]
