#!/bin/bash

# WARNING: DO NOT EDIT!
#
# This file was generated by plugin_template, and is managed by it. Please use
# './plugin-template --github pulp_file' to update this file.
#
# For more info visit https://github.com/pulp/plugin_template

# make sure this script runs at the repo root
cd "$(dirname "$(realpath -e "$0")")"/../..

set -euv

export VERSION=$(http pulp/pulp/api/v3/status/ | jq --arg plugin file -r '.versions[] | select(.component == $plugin) | .version')
export response=$(curl --write-out %{http_code} --silent --output /dev/null https://pypi.org/project/pulp-file-client/$VERSION/)
if [ "$response" == "200" ];
then
  echo "pulp_file $VERSION has already been released. Skipping."
  exit
fi

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
poetry publish --build --username pulp --password $PYPI_PASSWORD
